//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreLib.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoreLib.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Value must be between {0} and {1}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Between {
            get {
                return ResourceManager.GetString("Between", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot cast object of type &apos;{0}&apos; to &apos;{1}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CannotCastToType {
            get {
                return ResourceManager.GetString("CannotCastToType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Collection size ({0} items) exceeds maximum allowed count of {1} items に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CollectionSizeExceeded {
            get {
                return ResourceManager.GetString("CollectionSizeExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Component &apos;{0}&apos; is not properly initialized. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ComponentNotInitialized {
            get {
                return ResourceManager.GetString("ComponentNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Object &apos;{0}&apos; was created on thread {1} but accessed on thread {2}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CrossThreadOperation {
            get {
                return ResourceManager.GetString("CrossThreadOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data size ({0} bytes) exceeds maximum allowed size of {1} bytes ({2}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DataSizeExceeded {
            get {
                return ResourceManager.GetString("DataSizeExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Directory does not exist: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DirectoryNotFound {
            get {
                return ResourceManager.GetString("DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Directory is not writable: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DirectoryNotWritable {
            get {
                return ResourceManager.GetString("DirectoryNotWritable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value must be a valid email address. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EmailFormat {
            get {
                return ResourceManager.GetString("EmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your account has been locked. Please contact administrator. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorAccountLocked {
            get {
                return ResourceManager.GetString("ErrorAccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type &apos;{0}&apos; is not supported for AOT serialization. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorAotSerializationNotSupported {
            get {
                return ResourceManager.GetString("ErrorAotSerializationNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   API &apos;{0}&apos; is deprecated and will be removed in future versions. Use &apos;{1}&apos; instead. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorAPIDeprecated {
            get {
                return ResourceManager.GetString("ErrorAPIDeprecated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   API rate limit exceeded. Maximum rate: {0} requests per {1}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorAPIRateLimit {
            get {
                return ResourceManager.GetString("ErrorAPIRateLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Authentication failed. Please check your credentials. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorAuthenticationFailed {
            get {
                return ResourceManager.GetString("ErrorAuthenticationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to create backup. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorBackupFailed {
            get {
                return ResourceManager.GetString("ErrorBackupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bulk insert operation failed: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorBulkInsertFailed {
            get {
                return ResourceManager.GetString("ErrorBulkInsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bulk update operation failed: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorBulkUpdateFailed {
            get {
                return ResourceManager.GetString("ErrorBulkUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The certificate is invalid or has expired. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorCertificateInvalid {
            get {
                return ResourceManager.GetString("ErrorCertificateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to detect character encoding for the data. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorCharacterEncodingDetectionFailed {
            get {
                return ResourceManager.GetString("ErrorCharacterEncodingDetectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clock skew detected. Local time differs from server time by {0} seconds. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorClockSkew {
            get {
                return ResourceManager.GetString("ErrorClockSkew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Communication failure with remote system. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorCommunicationFailure {
            get {
                return ResourceManager.GetString("ErrorCommunicationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to read configuration file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorConfigReadFailed {
            get {
                return ResourceManager.GetString("ErrorConfigReadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to save configuration. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorConfigWriteFailed {
            get {
                return ResourceManager.GetString("ErrorConfigWriteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The connection was unexpectedly dropped. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorConnectionDropped {
            get {
                return ResourceManager.GetString("ErrorConnectionDropped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Container resource limit reached: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorContainerLimit {
            get {
                return ResourceManager.GetString("ErrorContainerLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CSV parsing failed at line {0}: {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorCSVParsingFailed {
            get {
                return ResourceManager.GetString("ErrorCSVParsingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Access denied to data resource &apos;{0}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorDataAccessDenied {
            get {
                return ResourceManager.GetString("ErrorDataAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Database connection pool limit reached. Current connections: {0}, Maximum: {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorDatabaseConnectionPool {
            get {
                return ResourceManager.GetString("ErrorDatabaseConnectionPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data binding failed for property &apos;{0}&apos;: {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorDataBindingFailed {
            get {
                return ResourceManager.GetString("ErrorDataBindingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data binding source is invalid or not supported. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorDataBindingSourceInvalid {
            get {
                return ResourceManager.GetString("ErrorDataBindingSourceInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data cache miss for key &apos;{0}&apos;. Object may have been evicted or expired. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorDataCacheMiss {
            get {
                return ResourceManager.GetString("ErrorDataCacheMiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data command execution failed: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorDataCommandFailed {
            get {
                return ResourceManager.GetString("ErrorDataCommandFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to connect to data source: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorDataConnectionFailed {
            get {
                return ResourceManager.GetString("ErrorDataConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data constraint violation: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorDataConstraintViolation {
            get {
                return ResourceManager.GetString("ErrorDataConstraintViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to convert data from &apos;{0}&apos; to &apos;{1}&apos;: {2} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorDataConversionFailed {
            get {
                return ResourceManager.GetString("ErrorDataConversionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data is corrupted and cannot be processed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorDataCorrupted {
            get {
                return ResourceManager.GetString("ErrorDataCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A deadlock was detected while accessing data. The transaction has been terminated. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorDataDeadlock {
            get {
                return ResourceManager.GetString("ErrorDataDeadlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dependency cycle detected in data processing pipeline: {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorDataDependencyCycle {
            get {
                return ResourceManager.GetString("ErrorDataDependencyCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data inconsistency detected. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorDataInconsistent {
            get {
                return ResourceManager.GetString("ErrorDataInconsistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data integrity violation: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorDataIntegrityViolation {
            get {
                return ResourceManager.GetString("ErrorDataIntegrityViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Optimistic concurrency control failed. The record has been modified since it was last retrieved. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorDataOptimisticLockingFailed {
            get {
                return ResourceManager.GetString("ErrorDataOptimisticLockingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dataset relation constraint violation: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorDatasetRelationViolation {
            get {
                return ResourceManager.GetString("ErrorDatasetRelationViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data source connection timeout after {0} seconds. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorDataSourceTimeout {
            get {
                return ResourceManager.GetString("ErrorDataSourceTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data stream compression failed: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorDataStreamCompression {
            get {
                return ResourceManager.GetString("ErrorDataStreamCompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data stream decompression failed: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorDataStreamDecompression {
            get {
                return ResourceManager.GetString("ErrorDataStreamDecompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data structure mismatch. Expected structure: &apos;{0}&apos;, Actual: &apos;{1}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorDataStructureMismatch {
            get {
                return ResourceManager.GetString("ErrorDataStructureMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data synchronization conflict detected: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorDataSyncConflict {
            get {
                return ResourceManager.GetString("ErrorDataSyncConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DataTable schema violation: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorDatatableSchemaViolation {
            get {
                return ResourceManager.GetString("ErrorDatatableSchemaViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data size exceeds the maximum allowed limit. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorDataTooLarge {
            get {
                return ResourceManager.GetString("ErrorDataTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data transaction was aborted: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorDataTransactionAborted {
            get {
                return ResourceManager.GetString("ErrorDataTransactionAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data type &apos;{0}&apos; is not supported for this operation. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorDataTypeNotSupported {
            get {
                return ResourceManager.GetString("ErrorDataTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data validation failed: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorDataValidationFailed {
            get {
                return ResourceManager.GetString("ErrorDataValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DateOnly value &apos;{0}&apos; is outside the supported range. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorDateOnlyOverflow {
            get {
                return ResourceManager.GetString("ErrorDateOnlyOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Device is busy: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorDeviceBusy {
            get {
                return ResourceManager.GetString("ErrorDeviceBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Device not found: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorDeviceNotFound {
            get {
                return ResourceManager.GetString("ErrorDeviceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Device is not responding: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorDeviceNotResponding {
            get {
                return ResourceManager.GetString("ErrorDeviceNotResponding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Domain trust relationship failure between &apos;{0}&apos; and &apos;{1}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorDomainTrustFailure {
            get {
                return ResourceManager.GetString("ErrorDomainTrustFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Domain &apos;{0}&apos; is unreachable. DNS resolution failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorDomainUnreachable {
            get {
                return ResourceManager.GetString("ErrorDomainUnreachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Required device driver is not installed: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorDriverNotInstalled {
            get {
                return ResourceManager.GetString("ErrorDriverNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value &apos;{0}&apos; is not a valid option for &apos;{1}&apos;. Valid options are: {2}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorEnumValueInvalid {
            get {
                return ResourceManager.GetString("ErrorEnumValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Required environment variable {0} not found or invalid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorEnvironmentVariable {
            get {
                return ResourceManager.GetString("ErrorEnvironmentVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Field &apos;{0}&apos; has incorrect type. Expected: {1}, Actual: {2}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorFieldTypeMismatch {
            get {
                return ResourceManager.GetString("ErrorFieldTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File system quota exceeded. Available space: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorFileSystemQuota {
            get {
                return ResourceManager.GetString("ErrorFileSystemQuota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File system is in read-only mode. Write operations are disabled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorFileSystemReadOnly {
            get {
                return ResourceManager.GetString("ErrorFileSystemReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Required framework not installed: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorFrameworkNotInstalled {
            get {
                return ResourceManager.GetString("ErrorFrameworkNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hardware fault detected: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorHardwareFault {
            get {
                return ResourceManager.GetString("ErrorHardwareFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The system is experiencing high CPU usage. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorHighCpuUsage {
            get {
                return ResourceManager.GetString("ErrorHighCpuUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Internationalization support for locale &apos;{0}&apos; is not installed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorI18NSupport {
            get {
                return ResourceManager.GetString("ErrorI18NSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Incompatible version. Required: {0}, Current: {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorIncompatibleVersion {
            get {
                return ResourceManager.GetString("ErrorIncompatibleVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You don&apos;t have sufficient rights to perform this action. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorInsufficientRights {
            get {
                return ResourceManager.GetString("ErrorInsufficientRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The configuration is invalid or corrupted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorInvalidConfiguration {
            get {
                return ResourceManager.GetString("ErrorInvalidConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data format &apos;{0}&apos; is invalid or not recognized. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorInvalidDataFormat {
            get {
                return ResourceManager.GetString("ErrorInvalidDataFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid data segment at offset {0}: {1}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorInvalidDataSegment {
            get {
                return ResourceManager.GetString("ErrorInvalidDataSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid garbage collection operation. The operation might interfere with the runtime. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorInvalidGCOperation {
            get {
                return ResourceManager.GetString("ErrorInvalidGCOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hardware acceleration is not available or failed to initialize: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorInvalidHardwareAcceleration {
            get {
                return ResourceManager.GetString("ErrorInvalidHardwareAcceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid JSON format at position {0}: {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorInvalidJson {
            get {
                return ResourceManager.GetString("ErrorInvalidJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid operation. This action cannot be performed at this time. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorInvalidOperation {
            get {
                return ResourceManager.GetString("ErrorInvalidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid setting: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorInvalidSetting {
            get {
                return ResourceManager.GetString("ErrorInvalidSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid Span operation. The operation might cause access violation. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorInvalidSpanOperation {
            get {
                return ResourceManager.GetString("ErrorInvalidSpanOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System is in an invalid state: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorInvalidSystemState {
            get {
                return ResourceManager.GetString("ErrorInvalidSystemState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid UTF-8 sequence detected at position {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorInvalidUtf8Sequence {
            get {
                return ResourceManager.GetString("ErrorInvalidUtf8Sequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid XML format: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorInvalidXml {
            get {
                return ResourceManager.GetString("ErrorInvalidXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JSON deserialization failed: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorJsonDeserializationFailed {
            get {
                return ResourceManager.GetString("ErrorJsonDeserializationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JsonNode type mismatch. Expected: &apos;{0}&apos;, Actual: &apos;{1}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorJsonNodeTypeIncorrect {
            get {
                return ResourceManager.GetString("ErrorJsonNodeTypeIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JSON polymorphic type resolution failed. Type discriminator &apos;{0}&apos; is invalid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorJsonPolymorphicTypeFailed {
            get {
                return ResourceManager.GetString("ErrorJsonPolymorphicTypeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Required JSON property &apos;{0}&apos; is missing. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorJsonPropertyMissing {
            get {
                return ResourceManager.GetString("ErrorJsonPropertyMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JSON schema validation error: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorJsonSchemaMismatch {
            get {
                return ResourceManager.GetString("ErrorJsonSchemaMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JSON serialization failed: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorJsonSerializationFailed {
            get {
                return ResourceManager.GetString("ErrorJsonSerializationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JSON source generation failed: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorJsonSourceGenerationFailed {
            get {
                return ResourceManager.GetString("ErrorJsonSourceGenerationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Required kernel module &apos;{0}&apos; is not loaded. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorKernelModuleNotLoaded {
            get {
                return ResourceManager.GetString("ErrorKernelModuleNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Low disk space. Only {0} MB available. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorLowDiskSpace {
            get {
                return ResourceManager.GetString("ErrorLowDiskSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Maximum number of concurrent sessions reached. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMaximumSessionsReached {
            get {
                return ResourceManager.GetString("ErrorMaximumSessionsReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Memory buffer is too small for the data processing operation. Required: {0} bytes, Available: {1} bytes. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMemoryBufferTooSmall {
            get {
                return ResourceManager.GetString("ErrorMemoryBufferTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Required data is missing or invalid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMissingData {
            get {
                return ResourceManager.GetString("ErrorMissingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Missing dependency: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMissingDependency {
            get {
                return ResourceManager.GetString("ErrorMissingDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Missing runtime pack for target framework &apos;{0}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMissingRuntimePack {
            get {
                return ResourceManager.GetString("ErrorMissingRuntimePack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Model validation failed with {0} error(s). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorModelValidationFailed {
            get {
                return ResourceManager.GetString("ErrorModelValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Native AOT compilation error: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorNativeAOTCompilation {
            get {
                return ResourceManager.GetString("ErrorNativeAOTCompilation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Network interface &apos;{0}&apos; is down or disconnected. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorNetworkInterfaceDown {
            get {
                return ResourceManager.GetString("ErrorNetworkInterfaceDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Significant network packet loss detected: {0}% に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorNetworkPacketLoss {
            get {
                return ResourceManager.GetString("ErrorNetworkPacketLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No response from server. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorNoResponse {
            get {
                return ResourceManager.GetString("ErrorNoResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Circular reference detected in object graph at &apos;{0}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorObjectGraphCircularReference {
            get {
                return ResourceManager.GetString("ErrorObjectGraphCircularReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not enough memory to complete this operation. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorOutOfMemory {
            get {
                return ResourceManager.GetString("ErrorOutOfMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parallel data processing failed with {0} tasks failed out of {1}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorParallelDataProcessingFailed {
            get {
                return ResourceManager.GetString("ErrorParallelDataProcessingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to parse data: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorParsingFailed {
            get {
                return ResourceManager.GetString("ErrorParsingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pattern matching failed. Value &apos;{0}&apos; does not match pattern &apos;{1}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorPatternMatchingFailed {
            get {
                return ResourceManager.GetString("ErrorPatternMatchingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Memory leak detected in process. Available memory decreasing over time. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorProcessMemoryLeak {
            get {
                return ResourceManager.GetString("ErrorProcessMemoryLeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Processor thermal throttling detected. Performance may be degraded. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorProcessorThermalThrottle {
            get {
                return ResourceManager.GetString("ErrorProcessorThermalThrottle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The process was terminated unexpectedly. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorProcessTerminated {
            get {
                return ResourceManager.GetString("ErrorProcessTerminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Protocol error: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorProtocolError {
            get {
                return ResourceManager.GetString("ErrorProtocolError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Record batch processing failed at batch {0}: {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorRecordBatchProcessingFailed {
            get {
                return ResourceManager.GetString("ErrorRecordBatchProcessingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Record validation failed: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorRecordValidationFailed {
            get {
                return ResourceManager.GetString("ErrorRecordValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recovery operation failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorRecoveryFailed {
            get {
                return ResourceManager.GetString("ErrorRecoveryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Referential integrity violation. {0} references {1} which does not exist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorReferentialIntegrityViolation {
            get {
                return ResourceManager.GetString("ErrorReferentialIntegrityViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to access the system registry. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorRegistryAccess {
            get {
                return ResourceManager.GetString("ErrorRegistryAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Required field &apos;{0}&apos; is missing or empty. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorRequiredFieldMissing {
            get {
                return ResourceManager.GetString("ErrorRequiredFieldMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System resource limit reached for: {0}. Current usage: {1}, Limit: {2} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorResourceLimitReached {
            get {
                return ResourceManager.GetString("ErrorResourceLimitReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to restore from backup. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorRestoreFailed {
            get {
                return ResourceManager.GetString("ErrorRestoreFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Security violation detected. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorSecurityViolation {
            get {
                return ResourceManager.GetString("ErrorSecurityViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Source-generated data context failed to initialize: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorSourceGeneratorDataContextFailed {
            get {
                return ResourceManager.GetString("ErrorSourceGeneratorDataContextFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Source generator failed: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorSourceGeneratorFailed {
            get {
                return ResourceManager.GetString("ErrorSourceGeneratorFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SSL/TLS error: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorSSLError {
            get {
                return ResourceManager.GetString("ErrorSSLError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The system is currently busy. Please try again later. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorSystemBusy {
            get {
                return ResourceManager.GetString("ErrorSystemBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System call &apos;{0}&apos; failed with error code: {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorSystemCallFailure {
            get {
                return ResourceManager.GetString("ErrorSystemCallFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System clock error detected. Current time may be inaccurate. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorSystemClock {
            get {
                return ResourceManager.GetString("ErrorSystemClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System is currently in maintenance mode until {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorSystemMaintenance {
            get {
                return ResourceManager.GetString("ErrorSystemMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System is in an unstable state. Restart recommended. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorSystemNotStable {
            get {
                return ResourceManager.GetString("ErrorSystemNotStable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System update required to run this application. Minimum required: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorSystemUpdateRequired {
            get {
                return ResourceManager.GetString("ErrorSystemUpdateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Task scheduler encountered an error: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorTaskSchedulerException {
            get {
                return ResourceManager.GetString("ErrorTaskSchedulerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Thread deadlock detected between threads: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorThreadDeadlock {
            get {
                return ResourceManager.GetString("ErrorThreadDeadlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Thread pool starvation detected. Consider adjusting thread pool settings. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorThreadPoolStarvation {
            get {
                return ResourceManager.GetString("ErrorThreadPoolStarvation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TimeOnly value &apos;{0}&apos; is outside the supported range. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorTimeOnlyOverflow {
            get {
                return ResourceManager.GetString("ErrorTimeOnlyOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This error requires troubleshooting. See log for details. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorTroubleshootingNeeded {
            get {
                return ResourceManager.GetString("ErrorTroubleshootingNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An unexpected error has occurred. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorUnexpected {
            get {
                return ResourceManager.GetString("ErrorUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown error occurred. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorUnknown {
            get {
                return ResourceManager.GetString("ErrorUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Encoding &apos;{0}&apos; is not supported. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorUnsupportedEncoding {
            get {
                return ResourceManager.GetString("ErrorUnsupportedEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This operation is not supported on this platform. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorUnsupportedPlatform {
            get {
                return ResourceManager.GetString("ErrorUnsupportedPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UTF-8 encoding operation exceeded buffer size of {0} bytes. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorUtf8EncodingOverflow {
            get {
                return ResourceManager.GetString("ErrorUtf8EncodingOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value &apos;{0}&apos; for &apos;{1}&apos; is out of range. Valid range: {2} to {3}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorValueOutOfRange {
            get {
                return ResourceManager.GetString("ErrorValueOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Virtual machine resource limit reached: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorVirtualMachineLimit {
            get {
                return ResourceManager.GetString("ErrorVirtualMachineLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XML deserialization failed: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorXmlDeserializationFailed {
            get {
                return ResourceManager.GetString("ErrorXmlDeserializationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Required XML element &apos;{0}&apos; is missing. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorXmlElementMissing {
            get {
                return ResourceManager.GetString("ErrorXmlElementMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XML schema validation error: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorXmlSchemaMismatch {
            get {
                return ResourceManager.GetString("ErrorXmlSchemaMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XML serialization failed: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorXmlSerializationFailed {
            get {
                return ResourceManager.GetString("ErrorXmlSerializationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Feature &apos;{0}&apos; is not implemented yet. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FeatureNotImplemented {
            get {
                return ResourceManager.GetString("FeatureNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File extension &apos;{0}&apos; is blocked. Blocked extensions are: {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileExtensionBlocked {
            get {
                return ResourceManager.GetString("FileExtensionBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File extension &apos;{0}&apos; is not allowed. Allowed extensions are: {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileExtensionNotAllowed {
            get {
                return ResourceManager.GetString("FileExtensionNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File does not exist: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File is not writable: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileNotWritable {
            get {
                return ResourceManager.GetString("FileNotWritable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File size ({0} bytes) exceeds maximum allowed size of {1} bytes ({2}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileSizeExceeded {
            get {
                return ResourceManager.GetString("FileSizeExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value must be greater than {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GreaterThan {
            get {
                return ResourceManager.GetString("GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Configuration &apos;{0}&apos; is invalid: {1}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidConfiguration {
            get {
                return ResourceManager.GetString("InvalidConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File name &apos;{0}&apos; contains invalid characters. Invalid characters include: {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidFileName {
            get {
                return ResourceManager.GetString("InvalidFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Invalid license for feature &apos;{0}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidLicense {
            get {
                return ResourceManager.GetString("InvalidLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Method &apos;{0}&apos; cannot be called in state &apos;{1}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidMethodCallForState {
            get {
                return ResourceManager.GetString("InvalidMethodCallForState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Path &apos;{0}&apos; contains invalid characters. Invalid characters include: {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidPath {
            get {
                return ResourceManager.GetString("InvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Port number {0} is outside the valid range (0-65535). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidPortRange {
            get {
                return ResourceManager.GetString("InvalidPortRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value must be less than {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LessThan {
            get {
                return ResourceManager.GetString("LessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Network connection is not available. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NetworkNotAvailable {
            get {
                return ResourceManager.GetString("NetworkNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   String cannot be null or empty. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotNullOrEmpty {
            get {
                return ResourceManager.GetString("NotNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   String cannot be null or whitespace. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("NotNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot access a disposed &apos;{0}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ObjectDisposed {
            get {
                return ResourceManager.GetString("ObjectDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Operation &apos;{0}&apos; was canceled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OperationCanceled {
            get {
                return ResourceManager.GetString("OperationCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Operation &apos;{0}&apos; failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OperationFailed {
            get {
                return ResourceManager.GetString("OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Operation &apos;{0}&apos; timed out after {1} seconds. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OperationTimedOut {
            get {
                return ResourceManager.GetString("OperationTimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to check port {0} availability: {1}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PortCheckFailed {
            get {
                return ResourceManager.GetString("PortCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Port {0} is already in use by another process. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PortInUse {
            get {
                return ResourceManager.GetString("PortInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Process &apos;{0}&apos; is already running. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProcessAlreadyRunning {
            get {
                return ResourceManager.GetString("ProcessAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Process with ID {0} has already exited. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProcessExited {
            get {
                return ResourceManager.GetString("ProcessExited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Process with ID {0} was not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProcessNotFound {
            get {
                return ResourceManager.GetString("ProcessNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This operation requires administrator privileges. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RequiresAdministrator {
            get {
                return ResourceManager.GetString("RequiresAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This operation must be performed on the UI thread. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RequiresUIThread {
            get {
                return ResourceManager.GetString("RequiresUIThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Service &apos;{0}&apos; was not found on this computer. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ServiceNotFound {
            get {
                return ResourceManager.GetString("ServiceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Service &apos;{0}&apos; is not running. Current status: {1}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ServiceNotRunning {
            get {
                return ResourceManager.GetString("ServiceNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stream is not readable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StreamNotReadable {
            get {
                return ResourceManager.GetString("StreamNotReadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stream is not writable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StreamNotWritable {
            get {
                return ResourceManager.GetString("StreamNotWritable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stream size ({0} bytes) exceeds maximum allowed size of {1} bytes ({2}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StreamSizeExceeded {
            get {
                return ResourceManager.GetString("StreamSizeExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   String length ({0} characters) exceeds maximum allowed length of {1} characters に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StringLengthExceeded {
            get {
                return ResourceManager.GetString("StringLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Task &apos;{0}&apos; was canceled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TaskCanceled {
            get {
                return ResourceManager.GetString("TaskCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Task &apos;{0}&apos; failed with error: {1}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TaskFaulted {
            get {
                return ResourceManager.GetString("TaskFaulted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Task &apos;{0}&apos; has not completed yet. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TaskNotCompleted {
            get {
                return ResourceManager.GetString("TaskNotCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This feature requires Windows version {0} or later. Current version: {1}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WindowsVersionRequired {
            get {
                return ResourceManager.GetString("WindowsVersionRequired", resourceCulture);
            }
        }
    }
}
