//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreLib.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoreLib.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Value must be between {0} and {1}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Between {
            get {
                return ResourceManager.GetString("Between", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot cast object of type &apos;{0}&apos; to &apos;{1}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CannotCastToType {
            get {
                return ResourceManager.GetString("CannotCastToType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Collection size ({0} items) exceeds maximum allowed count of {1} items に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CollectionSizeExceeded {
            get {
                return ResourceManager.GetString("CollectionSizeExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Component &apos;{0}&apos; is not properly initialized. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ComponentNotInitialized {
            get {
                return ResourceManager.GetString("ComponentNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Object &apos;{0}&apos; was created on thread {1} but accessed on thread {2}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CrossThreadOperation {
            get {
                return ResourceManager.GetString("CrossThreadOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data size ({0} bytes) exceeds maximum allowed size of {1} bytes ({2}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DataSizeExceeded {
            get {
                return ResourceManager.GetString("DataSizeExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Directory does not exist: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DirectoryNotFound {
            get {
                return ResourceManager.GetString("DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Directory is not writable: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DirectoryNotWritable {
            get {
                return ResourceManager.GetString("DirectoryNotWritable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value must be a valid email address. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EmailFormat {
            get {
                return ResourceManager.GetString("EmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your account has been locked. Please contact administrator. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorAccountLocked {
            get {
                return ResourceManager.GetString("ErrorAccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Authentication failed. Please check your credentials. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorAuthenticationFailed {
            get {
                return ResourceManager.GetString("ErrorAuthenticationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to create backup. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorBackupFailed {
            get {
                return ResourceManager.GetString("ErrorBackupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The certificate is invalid or has expired. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorCertificateInvalid {
            get {
                return ResourceManager.GetString("ErrorCertificateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Communication failure with remote system. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorCommunicationFailure {
            get {
                return ResourceManager.GetString("ErrorCommunicationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to read configuration file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorConfigReadFailed {
            get {
                return ResourceManager.GetString("ErrorConfigReadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to save configuration. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorConfigWriteFailed {
            get {
                return ResourceManager.GetString("ErrorConfigWriteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The connection was unexpectedly dropped. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorConnectionDropped {
            get {
                return ResourceManager.GetString("ErrorConnectionDropped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data is corrupted and cannot be processed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorDataCorrupted {
            get {
                return ResourceManager.GetString("ErrorDataCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data inconsistency detected. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorDataInconsistent {
            get {
                return ResourceManager.GetString("ErrorDataInconsistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data size exceeds the maximum allowed limit. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorDataTooLarge {
            get {
                return ResourceManager.GetString("ErrorDataTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data validation failed: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorDataValidationFailed {
            get {
                return ResourceManager.GetString("ErrorDataValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Device is busy: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorDeviceBusy {
            get {
                return ResourceManager.GetString("ErrorDeviceBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Device not found: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorDeviceNotFound {
            get {
                return ResourceManager.GetString("ErrorDeviceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Device is not responding: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorDeviceNotResponding {
            get {
                return ResourceManager.GetString("ErrorDeviceNotResponding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Required device driver is not installed: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorDriverNotInstalled {
            get {
                return ResourceManager.GetString("ErrorDriverNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Required environment variable {0} not found or invalid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorEnvironmentVariable {
            get {
                return ResourceManager.GetString("ErrorEnvironmentVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Required framework not installed: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorFrameworkNotInstalled {
            get {
                return ResourceManager.GetString("ErrorFrameworkNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hardware fault detected: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorHardwareFault {
            get {
                return ResourceManager.GetString("ErrorHardwareFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The system is experiencing high CPU usage. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorHighCpuUsage {
            get {
                return ResourceManager.GetString("ErrorHighCpuUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Incompatible version. Required: {0}, Current: {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorIncompatibleVersion {
            get {
                return ResourceManager.GetString("ErrorIncompatibleVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You don&apos;t have sufficient rights to perform this action. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorInsufficientRights {
            get {
                return ResourceManager.GetString("ErrorInsufficientRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The configuration is invalid or corrupted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorInvalidConfiguration {
            get {
                return ResourceManager.GetString("ErrorInvalidConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid operation. This action cannot be performed at this time. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorInvalidOperation {
            get {
                return ResourceManager.GetString("ErrorInvalidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid setting: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorInvalidSetting {
            get {
                return ResourceManager.GetString("ErrorInvalidSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Low disk space. Only {0} MB available. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorLowDiskSpace {
            get {
                return ResourceManager.GetString("ErrorLowDiskSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Required data is missing or invalid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMissingData {
            get {
                return ResourceManager.GetString("ErrorMissingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Missing dependency: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMissingDependency {
            get {
                return ResourceManager.GetString("ErrorMissingDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No response from server. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorNoResponse {
            get {
                return ResourceManager.GetString("ErrorNoResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not enough memory to complete this operation. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorOutOfMemory {
            get {
                return ResourceManager.GetString("ErrorOutOfMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to parse data: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorParsingFailed {
            get {
                return ResourceManager.GetString("ErrorParsingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The process was terminated unexpectedly. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorProcessTerminated {
            get {
                return ResourceManager.GetString("ErrorProcessTerminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Protocol error: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorProtocolError {
            get {
                return ResourceManager.GetString("ErrorProtocolError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recovery operation failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorRecoveryFailed {
            get {
                return ResourceManager.GetString("ErrorRecoveryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to access the system registry. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorRegistryAccess {
            get {
                return ResourceManager.GetString("ErrorRegistryAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to restore from backup. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorRestoreFailed {
            get {
                return ResourceManager.GetString("ErrorRestoreFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Security violation detected. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorSecurityViolation {
            get {
                return ResourceManager.GetString("ErrorSecurityViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SSL/TLS error: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorSSLError {
            get {
                return ResourceManager.GetString("ErrorSSLError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The system is currently busy. Please try again later. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorSystemBusy {
            get {
                return ResourceManager.GetString("ErrorSystemBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System is in an unstable state. Restart recommended. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorSystemNotStable {
            get {
                return ResourceManager.GetString("ErrorSystemNotStable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This error requires troubleshooting. See log for details. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorTroubleshootingNeeded {
            get {
                return ResourceManager.GetString("ErrorTroubleshootingNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An unexpected error has occurred. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorUnexpected {
            get {
                return ResourceManager.GetString("ErrorUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown error occurred. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorUnknown {
            get {
                return ResourceManager.GetString("ErrorUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This operation is not supported on this platform. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorUnsupportedPlatform {
            get {
                return ResourceManager.GetString("ErrorUnsupportedPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Feature &apos;{0}&apos; is not implemented yet. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FeatureNotImplemented {
            get {
                return ResourceManager.GetString("FeatureNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File extension &apos;{0}&apos; is blocked. Blocked extensions are: {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileExtensionBlocked {
            get {
                return ResourceManager.GetString("FileExtensionBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File extension &apos;{0}&apos; is not allowed. Allowed extensions are: {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileExtensionNotAllowed {
            get {
                return ResourceManager.GetString("FileExtensionNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File does not exist: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File is not writable: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileNotWritable {
            get {
                return ResourceManager.GetString("FileNotWritable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File size ({0} bytes) exceeds maximum allowed size of {1} bytes ({2}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileSizeExceeded {
            get {
                return ResourceManager.GetString("FileSizeExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value must be greater than {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GreaterThan {
            get {
                return ResourceManager.GetString("GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Configuration &apos;{0}&apos; is invalid: {1}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidConfiguration {
            get {
                return ResourceManager.GetString("InvalidConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File name &apos;{0}&apos; contains invalid characters. Invalid characters include: {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidFileName {
            get {
                return ResourceManager.GetString("InvalidFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Invalid license for feature &apos;{0}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidLicense {
            get {
                return ResourceManager.GetString("InvalidLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Method &apos;{0}&apos; cannot be called in state &apos;{1}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidMethodCallForState {
            get {
                return ResourceManager.GetString("InvalidMethodCallForState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Path &apos;{0}&apos; contains invalid characters. Invalid characters include: {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidPath {
            get {
                return ResourceManager.GetString("InvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Port number {0} is outside the valid range (0-65535). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidPortRange {
            get {
                return ResourceManager.GetString("InvalidPortRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value must be less than {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LessThan {
            get {
                return ResourceManager.GetString("LessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Network connection is not available. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NetworkNotAvailable {
            get {
                return ResourceManager.GetString("NetworkNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   String cannot be null or empty. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotNullOrEmpty {
            get {
                return ResourceManager.GetString("NotNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   String cannot be null or whitespace. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("NotNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot access a disposed &apos;{0}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ObjectDisposed {
            get {
                return ResourceManager.GetString("ObjectDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Operation &apos;{0}&apos; was canceled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OperationCanceled {
            get {
                return ResourceManager.GetString("OperationCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Operation &apos;{0}&apos; failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OperationFailed {
            get {
                return ResourceManager.GetString("OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Operation &apos;{0}&apos; timed out after {1} seconds. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OperationTimedOut {
            get {
                return ResourceManager.GetString("OperationTimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to check port {0} availability: {1}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PortCheckFailed {
            get {
                return ResourceManager.GetString("PortCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Port {0} is already in use by another process. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PortInUse {
            get {
                return ResourceManager.GetString("PortInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Process &apos;{0}&apos; is already running. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProcessAlreadyRunning {
            get {
                return ResourceManager.GetString("ProcessAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Process with ID {0} has already exited. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProcessExited {
            get {
                return ResourceManager.GetString("ProcessExited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Process with ID {0} was not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProcessNotFound {
            get {
                return ResourceManager.GetString("ProcessNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This operation requires administrator privileges. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RequiresAdministrator {
            get {
                return ResourceManager.GetString("RequiresAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This operation must be performed on the UI thread. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RequiresUIThread {
            get {
                return ResourceManager.GetString("RequiresUIThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Service &apos;{0}&apos; was not found on this computer. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ServiceNotFound {
            get {
                return ResourceManager.GetString("ServiceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Service &apos;{0}&apos; is not running. Current status: {1}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ServiceNotRunning {
            get {
                return ResourceManager.GetString("ServiceNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stream is not readable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StreamNotReadable {
            get {
                return ResourceManager.GetString("StreamNotReadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stream is not writable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StreamNotWritable {
            get {
                return ResourceManager.GetString("StreamNotWritable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stream size ({0} bytes) exceeds maximum allowed size of {1} bytes ({2}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StreamSizeExceeded {
            get {
                return ResourceManager.GetString("StreamSizeExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   String length ({0} characters) exceeds maximum allowed length of {1} characters に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StringLengthExceeded {
            get {
                return ResourceManager.GetString("StringLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Task &apos;{0}&apos; was canceled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TaskCanceled {
            get {
                return ResourceManager.GetString("TaskCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Task &apos;{0}&apos; failed with error: {1}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TaskFaulted {
            get {
                return ResourceManager.GetString("TaskFaulted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Task &apos;{0}&apos; has not completed yet. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TaskNotCompleted {
            get {
                return ResourceManager.GetString("TaskNotCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This feature requires Windows version {0} or later. Current version: {1}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WindowsVersionRequired {
            get {
                return ResourceManager.GetString("WindowsVersionRequired", resourceCulture);
            }
        }
    }
}
