//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreLib.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoreLib.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   A backup of the original file has been created at &apos;{0}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileBackupCreated {
            get {
                return ResourceManager.GetString("FileBackupCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is not enough disk space to save the file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileDiskFullError {
            get {
                return ResourceManager.GetString("FileDiskFullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file cannot be saved because it is being used by another process. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileInUseError {
            get {
                return ResourceManager.GetString("FileInUseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file name contains invalid characters. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileInvalidNameChars {
            get {
                return ResourceManager.GetString("FileInvalidNameChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please specify a file name. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileNotSpecified {
            get {
                return ResourceManager.GetString("FileNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file &apos;{0}&apos; already exists. Do you want to overwrite it? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileOverwriteConfirmation {
            get {
                return ResourceManager.GetString("FileOverwriteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file path is too long. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FilePathTooLong {
            get {
                return ResourceManager.GetString("FilePathTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You don&apos;t have permission to save the file to this location. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FilePermissionError {
            get {
                return ResourceManager.GetString("FilePermissionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file is read-only and cannot be saved. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileReadOnly {
            get {
                return ResourceManager.GetString("FileReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save As... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileSaveAs {
            get {
                return ResourceManager.GetString("FileSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to save changes to &apos;{0}&apos;? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileSaveChangesConfirmation {
            get {
                return ResourceManager.GetString("FileSaveChangesConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File saved with warnings: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileSaveCompletedWithWarning {
            get {
                return ResourceManager.GetString("FileSaveCompletedWithWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error occurred while saving the file: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileSaveErrorFormat {
            get {
                return ResourceManager.GetString("FileSaveErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to save the file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileSaveFailed {
            get {
                return ResourceManager.GetString("FileSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select where to save the file: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileSaveLocation {
            get {
                return ResourceManager.GetString("FileSaveLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File has been successfully saved. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileSaveSuccessful {
            get {
                return ResourceManager.GetString("FileSaveSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Saving file... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileSaving {
            get {
                return ResourceManager.GetString("FileSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A temporary copy has been saved. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileTemporarySaved {
            get {
                return ResourceManager.GetString("FileTemporarySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are unsaved changes. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileUnsavedChanges {
            get {
                return ResourceManager.GetString("FileUnsavedChanges", resourceCulture);
            }
        }
    }
}
